In [1]:
from pathlib import Path
from eoflow.ea import EAWaterQualityAPI, get_ea_water_quality
from eoflow.utils import load_shapefile
import folium

In [2]:
try:
    file_path = Path(__file__).resolve()
except NameError:
    file_path = Path.cwd()

shapefile_path = file_path.parent.parent.parent / "data/Counties_and_Unitary_Authorities_December_2023_Boundaries"
assert shapefile_path.is_dir()

In [23]:
shapefile_path

PosixPath('/home/finley/Work/RDS/projects/enforce/data/Counties_and_Unitary_Authorities_December_2023_Boundaries')

In [3]:
gdf = load_shapefile(path=shapefile_path)
devon_gdf = gdf[gdf["CTYUA23NM"] == "Devon"]
devon_gdf

,CTYUA23CD,CTYUA23NM,CTYUA23NMW,BNG_E,BNG_N,LONG,LAT,GlobalID,geometry
134,E10000008,Devon,None,283143,93085,-3.65698,50.7256,7aa8a35e-fa29-49bf-ac91-e4b121754500,"MULTIPOLYGON (((264838.577 43779.215, 264643.3..."

In [9]:

devon_gdf = devon_gdf.to_crs(epsg=4326)

# # Compute a sensible center for the map
geom_name = devon_gdf.geometry.name
centroid = devon_gdf.geometry.unary_union.centroid
map_center = [centroid.y, centroid.x]

# tooltip_fields = [c for c in gdf.columns if c != geom_name][:5]
# tooltip = folium.GeoJsonTooltip(fields=tooltip_fields, aliases=tooltip_fields) if tooltip_fields else None

m = folium.Map(
    location=map_center, 
    zoom_start=9,
    width="100%",
    height="500px",
    scrollWheelZoom=False)

folium.GeoJson(
    devon_gdf.__geo_interface__,
    name="shapefile",
    style_function=lambda feat: {
        "fillColor": "#ff7800",
        "color": "black",
        "weight": 0.5,
        "fillOpacity": 0.4,
    },
).add_to(m)

folium.LayerControl().add_to(m)

# Display the map
m

/tmp/ipykernel_210355/1854933694.py:5: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  centroid = devon_gdf.geometry.unary_union.centroid

In [24]:
import pandas as pd

In [26]:
ea_df = pd.read_csv("../devon_water_quality.csv")

In [27]:
ea_df.head()

,id,samplingPoint.notation,samplingPoint.prefLabel,samplingPoint.easting,samplingPoint.northing,samplingPoint.region,samplingPoint.area,samplingPoint.subArea,samplingPoint.samplingPointStatus,samplingPoint.samplingPointType,phenomenonTime,samplingPurpose,sampleMaterialType,determinand.notation,determinand.prefLabel,result,unit,Date,result_numeric
0,https://environment.data.gov.uk/water-quality/...,SW-70420116,RIVER OTTER AT DOTTON MILL,308730,88570,SouthWest,SOUTH WEST - DEVON AND CORNWALL,EAST DEVON AND CORNWALL,OPEN,FRESHWATER - RIVERS,2020-01-14 10:11:00,MONITORING (UK GOVT POLICY - NOT GQA OR RE),RIVER / RUNNING SURFACE WATER,6396,Turbidity,57.0,NEPHELOMETRIC TURBIDITY UNITS,2020-01-14,57.0
1,https://environment.data.gov.uk/water-quality/...,SW-70540110,RIVER EXE AT TREWS WEIR EXETER,292546,91506,SouthWest,SOUTH WEST - DEVON AND CORNWALL,EAST DEVON AND CORNWALL,OPEN,FRESHWATER - RIVERS,2020-01-22 11:36:00,MONITORING (UK GOVT POLICY - NOT GQA OR RE),RIVER / RUNNING SURFACE WATER,6396,Turbidity,8.6,NEPHELOMETRIC TURBIDITY UNITS,2020-01-22,8.6
2,https://environment.data.gov.uk/water-quality/...,SW-70540224,RIVER EXE AT THORVERTON GAUGING STATION,293608,101640,SouthWest,SOUTH WEST - DEVON AND CORNWALL,EAST DEVON AND CORNWALL,OPEN,FRESHWATER - RIVERS,2020-01-20 11:57:00,ENVIRONMENTAL MONITORING STATUTORY (EU DIRECTI...,RIVER / RUNNING SURFACE WATER,6396,Turbidity,5.9,NEPHELOMETRIC TURBIDITY UNITS,2020-01-20,5.9
3,https://environment.data.gov.uk/water-quality/...,SW-70620154,RIVER TEIGN AT PRESTON,285580,74543,SouthWest,SOUTH WEST - DEVON AND CORNWALL,CENTRAL DEVON AND CORNWALL,OPEN,FRESHWATER - RIVERS,2020-01-09 11:21:00,ENVIRONMENTAL MONITORING STATUTORY (EU DIRECTI...,RIVER / RUNNING SURFACE WATER,6396,Turbidity,15.0,NEPHELOMETRIC TURBIDITY UNITS,2020-01-09,15.0
4,https://environment.data.gov.uk/water-quality/...,SW-70631918,KENNICK STREAM AT TOTTIFORD RESERVOIR SURFACE,281060,82710,SouthWest,SOUTH WEST - DEVON AND CORNWALL,CENTRAL DEVON AND CORNWALL,OPEN,FRESHWATER - RIVERS,2020-01-10 15:32:00,UNPLANNED REACTIVE MONITORING (POLLUTION INCID...,POND / LAKE / RESERVOIR WATER,6396,Turbidity,1.7,NEPHELOMETRIC TURBIDITY UNITS,2020-01-10,1.7